services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: grocery
      POSTGRES_PASSWORD: grocery
      POSTGRES_DB: grocery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c wal_level=logical

volumes:
  postgres-data:
